### ISSUE TITLE
Deal with extremely long sentence in paper list

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#1]

**Comment by shanzhenren** [comment]
We could chunk the sentence by using the em/rm's left 6-word, right 6-word as limit.

**Comment by shanzhenren** [comment]
Pleas also "bold" the EMs in the sentence for highlight

**Comment by mickeystroller** [comment]
long sentence: fixed by showing context-window of entity mention. For sentence length < 300, just return as a whole.

(1) unable to do this without HTML escaping in the current framework, postponed later.
(2) fixed.
(3) current DB select 10 papers and I will de-duplicate it. I am unable to change the precise number of returned papers. 

See commit: 5712e3fc16c17586633d26ee67b5bd765af27da0

**Comment by shanzhenren** [comment]
Let's figure out the HTML escaping thing

**Comment by mickeystroller** [comment]
Add the HTML escaping and long sentence segmentation for relation. See commit: 50a4c24180978ad817d7f782a8864fb1b0bb04fe
